# Agent 7 -- Extracurricular Agent

**What Agent 7 does:** scores a candidate's non-academic profile -- leadership, research/publications, competitions, volunteering -- into a strength tier and a continuous `profile_strength_score`, and separately evaluates their Statement of Purpose / Letters of Recommendation.

**Input:** a candidate's raw achievement fields (leadership/research/competition/volunteering scores, publication and patent counts, degree level, field of study) and, where available, SOP/LOR text plus the target program's description (from Agent 3).

**Processing:**
1. Group candidates into achievement archetypes via KMeans clustering on their raw category scores (Section 2b) -- an unsupervised grouping that captures a candidate's overall *shape* of activity rather than just its magnitude, used as an additional feature below.
2. Classify the candidate into a strength tier (Weak / Moderate / Strong) and predict a continuous `profile_strength_score`, using a model compared and tuned across several families.
3. Score the SOP/LOR through three layers: structural checks, semantic alignment to the target program, and an LLM rubric pass.
4. Blend the SOP/LOR score into the final `profile_strength_score`, using a weight calibrated against real data (Section 8a) rather than guessed.

**On synthetic data (read this first):** no public dataset pairs individual leadership/competition/volunteering/publication records with real admission outcomes -- that data is privately held by institutions. Sections 1-7 train on a synthetic candidate-achievement dataset with a documented weighted-rubric label, which is why its accuracy numbers describe how well the model learned that rubric, not real committee judgment. Section 8a is the one part of this notebook informed by real, public data: the Kaggle Graduate Admissions dataset (500 real records with real SOP/LOR/Research fields and real outcomes) is used to replace a previously-guessed SOP weight with an evidence-based one. Section 11 remains the path to validating the rest against reality once real, human-reviewed candidates exist.

**Output:** `{strength_tier, profile_strength_score, sop_score, achievement_archetype, explainability}`, written to `state["extracurricular"]`.

**Connected agents:** its output feeds Agent 2 (as a classifier feature, `extracurricular_score`) and Agent 5 (merit-based scholarship eligibility); its SOP scoring sub-module reuses the embedding model Agent 2 and Agent 3 load.

## 0. Synthetic training data

In [1]:
import numpy as np
import pandas as pd

RNG = np.random.default_rng(42)
N = 4000

def gen_synthetic_extracurricular_data(n=N, rng=RNG):
    leadership_score = np.clip(rng.normal(5, 2.3, n), 0, 10)
    research_score = np.clip(rng.normal(4, 2.6, n), 0, 10)
    competition_score = np.clip(rng.normal(3.5, 2.4, n), 0, 10)
    volunteering_score = np.clip(rng.normal(4.5, 2.2, n), 0, 10)

    publication_count = rng.poisson(0.6, n)
    patent_count = rng.poisson(0.08, n)
    has_research_evidence = ((publication_count > 0) | (patent_count > 0)).astype(int)

    degree_level = rng.choice(["Bachelors", "Masters", "PhD-applicant"], size=n, p=[0.55, 0.35, 0.10])
    field = rng.choice(["STEM", "Business", "SocialSci", "Arts", "Other"], size=n,
                        p=[0.45, 0.22, 0.15, 0.10, 0.08])

    composite = (
        0.28 * leadership_score
        + 0.24 * research_score
        + 0.16 * competition_score
        + 0.14 * volunteering_score
        + 6.0 * np.log1p(publication_count)
        + 10.0 * np.log1p(patent_count)
        + rng.normal(0, 3.0, n)
    )
    profile_strength_score = np.clip(composite / composite.max() * 100, 0, 100)
    strength_tier = np.where(profile_strength_score >= 65, "Strong",
                     np.where(profile_strength_score >= 40, "Moderate", "Weak"))

    df = pd.DataFrame({
        "candidate_id": [f"C{i:05d}" for i in range(n)],
        "degree_level": degree_level,
        "field": field,
        "leadership_score": leadership_score.round(2),
        "research_score": research_score.round(2),
        "competition_score": competition_score.round(2),
        "volunteering_score": volunteering_score.round(2),
        "publication_count": publication_count,
        "patent_count": patent_count,
        "has_research_evidence": has_research_evidence,
        "profile_strength_score": profile_strength_score.round(2),
        "strength_tier": strength_tier,
    })
    return df

DATA_PATH = "agent7_extracurricular_synthetic.csv"
df = gen_synthetic_extracurricular_data()
df.to_csv(DATA_PATH, index=False)
print("Shape:", df.shape)
df.head()

Shape: (4000, 12)

,candidate_id,degree_level,field,leadership_score,research_score,competition_score,volunteering_score,publication_count,patent_count,has_research_evidence,profile_strength_score,strength_tier
0,C00000,Masters,SocialSci,5.70,4.66,4.30,3.82,1,1,1,62.30,Moderate
1,C00001,Masters,STEM,2.61,6.33,6.47,4.63,0,0,0,30.77,Weak
2,C00002,Masters,Business,6.73,4.71,6.42,1.77,0,0,0,18.77,Weak
3,C00003,Bachelors,Business,7.16,9.82,2.42,1.45,1,0,1,35.33,Weak
4,C00004,Bachelors,SocialSci,0.51,7.72,3.97,4.90,1,0,1,25.59,Weak

## 1. Load and explore the data

In [2]:
df = pd.read_csv(DATA_PATH)
print(df.dtypes)
print()
print("Missing values per column:")
print(df.isnull().sum())

candidate_id                  str
degree_level                  str
field                         str
leadership_score          float64
research_score            float64
competition_score         float64
volunteering_score        float64
publication_count           int64
patent_count                int64
has_research_evidence       int64
profile_strength_score    float64
strength_tier                 str
dtype: object

Missing values per column:
candidate_id              0
degree_level              0
field                     0
leadership_score          0
research_score            0
competition_score         0
volunteering_score        0
publication_count         0
patent_count              0
has_research_evidence     0
profile_strength_score    0
strength_tier             0
dtype: int64

In [3]:
print("Degree level distribution:")
print(df["degree_level"].value_counts())
print()
print("Strength tier distribution:")
print(df["strength_tier"].value_counts())
print()
print("Tier distribution by degree level:")
print(df.groupby("degree_level")["strength_tier"].value_counts())

Degree level distribution:
degree_level
Bachelors        2196
Masters          1411
PhD-applicant     393
Name: count, dtype: int64

Strength tier distribution:
strength_tier
Weak        2843
Moderate     983
Strong       174
Name: count, dtype: int64

Tier distribution by degree level:
degree_level   strength_tier
Bachelors      Weak             1560
               Moderate          542
               Strong             94
Masters        Weak              993
               Moderate          352
               Strong             66
PhD-applicant  Weak              290
               Moderate           89
               Strong             14
Name: count, dtype: int64

### Sanity check: confirm `profile_strength_score` is a leakage risk if kept raw
Like Agent 1's `profile_score`, `profile_strength_score` is a near-deterministic weighted sum of the category scores below it, and `strength_tier` is a threshold rule on it (~65 / ~40). It is used only as the training **label**, never as a feature.

In [4]:
corr_cols = ["leadership_score", "research_score", "competition_score",
             "volunteering_score", "publication_count", "patent_count",
             "profile_strength_score"]
print(df[corr_cols].corr()["profile_strength_score"])

leadership_score          0.125102
research_score            0.120482
competition_score         0.076898
volunteering_score        0.069241
publication_count         0.568162
patent_count              0.404532
profile_strength_score    1.000000
Name: profile_strength_score, dtype: float64

## 2. Preprocessing

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import xgboost as xgb
import joblib
import time

pd.set_option("display.max_columns", None)

model_df = df.drop(columns=["candidate_id", "profile_strength_score"])

y = model_df["strength_tier"]
X = model_df.drop(columns=["strength_tier"])

numeric_cols = ["leadership_score", "research_score", "competition_score",
                 "volunteering_score", "publication_count", "patent_count",
                 "has_research_evidence"]
cat_cols = ["degree_level", "field"]

for c in numeric_cols:
    X[c] = X[c].fillna(0)
for c in cat_cols:
    X[c] = X[c].fillna("NA")

X_encoded = pd.get_dummies(X, columns=cat_cols)
print(X_encoded.shape)
X_encoded.head()

(4000, 15)

,leadership_score,research_score,competition_score,volunteering_score,publication_count,patent_count,has_research_evidence,degree_level_Bachelors,degree_level_Masters,degree_level_PhD-applicant,field_Arts,field_Business,field_Other,field_STEM,field_SocialSci
0,5.70,4.66,4.30,3.82,1,1,1,False,True,False,False,False,False,False,True
1,2.61,6.33,6.47,4.63,0,0,0,False,True,False,False,False,False,True,False
2,6.73,4.71,6.42,1.77,0,0,0,False,True,False,False,True,False,False,False
3,7.16,9.82,2.42,1.45,1,0,1,True,False,False,False,True,False,False,False
4,0.51,7.72,3.97,4.90,1,0,1,True,False,False,False,False,False,False,True

### 2b. Achievement archetype clustering (KMeans)
Groups candidates into achievement archetypes by running KMeans over their (standardized) raw category scores, with the cluster count chosen by silhouette score. Captures a candidate's overall *shape* of activity (e.g. concentrated in research vs. spread across leadership and volunteering) in a way no single raw score does, and is added to the feature set the classifier trains on below.

In [6]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

CLUSTER_COLS = ["leadership_score", "research_score", "competition_score",
                "volunteering_score", "publication_count", "patent_count"]

cluster_scaler = StandardScaler()
cluster_input_scaled = cluster_scaler.fit_transform(X_encoded[CLUSTER_COLS])

best_k, best_silhouette = None, -1
for k in range(3, 9):
    labels = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(cluster_input_scaled)
    score = silhouette_score(cluster_input_scaled, labels)
    if score > best_silhouette:
        best_k, best_silhouette = k, score

print(f"Selected k={best_k} achievement archetypes (silhouette={best_silhouette:.3f})")

archetype_kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10).fit(cluster_input_scaled)
X_encoded["achievement_archetype"] = archetype_kmeans.labels_.astype(str)

archetype_profile = df.loc[X_encoded.index, CLUSTER_COLS].copy()
archetype_profile["achievement_archetype"] = X_encoded["achievement_archetype"].values
print(archetype_profile.groupby("achievement_archetype").mean().round(2))

X_encoded = pd.get_dummies(X_encoded, columns=["achievement_archetype"])
print("\nX_encoded shape after adding archetype dummies:", X_encoded.shape)

Selected k=4 achievement archetypes (silhouette=0.171)
                       leadership_score  research_score  competition_score  \
achievement_archetype
0                                  4.92            3.98               3.47
1                                  4.12            3.81               5.39
2                                  4.73            4.01               3.45
3                                  5.72            4.31               1.98

                       volunteering_score  publication_count  patent_count
achievement_archetype
0                                    4.66               2.25          0.00
1                                    4.69               0.39          0.00
2                                    4.41               0.57          1.03
3                                    4.32               0.38          0.00

X_encoded shape after adding archetype dummies: (4000, 19)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)
print("Train size:", X_train.shape, " Test size:", X_test.shape)

Train size: (3200, 19)  Test size: (800, 19)

## 3. Model comparison

In [8]:
candidate_models = {
    "Logistic Regression": (LogisticRegression(max_iter=2000), True),
    "Random Forest": (RandomForestClassifier(n_estimators=300, max_depth=8, min_samples_leaf=5, random_state=42, n_jobs=-1), False),
    "Gradient Boosting (sklearn)": (GradientBoostingClassifier(random_state=42), False),
    "XGBoost": (xgb.XGBClassifier(n_estimators=300, max_depth=4, learning_rate=0.1, random_state=42, eval_metric="mlogloss"), False),
    "SVM (RBF)": (SVC(probability=True, random_state=42), True),
    "KNN (k=15)": (KNeighborsClassifier(n_neighbors=15, weights="distance"), True),
}

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

y_train_enc = y_train.map({"Weak": 0, "Moderate": 1, "Strong": 2})
y_test_enc = y_test.map({"Weak": 0, "Moderate": 1, "Strong": 2})

comparison_results = []
fitted_models = {}
for name, (model, needs_scaling) in candidate_models.items():
    Xtr = X_train_s if needs_scaling else X_train
    Xte = X_test_s if needs_scaling else X_test
    ytr = y_train_enc if name == "XGBoost" else y_train

    t0 = time.time()
    model.fit(Xtr, ytr)
    train_time = time.time() - t0

    pred = model.predict(Xte)
    if name == "XGBoost":
        pred_labels = pd.Series(pred).map({0: "Weak", 1: "Moderate", 2: "Strong"})
    else:
        pred_labels = pred

    acc = (pd.Series(pred_labels).values == y_test.values).mean()
    fitted_models[name] = model
    comparison_results.append({"model": name, "accuracy": round(acc, 4), "train_time_s": round(train_time, 3)})

comparison_df = pd.DataFrame(comparison_results).sort_values("accuracy", ascending=False)
print(comparison_df)

                         model  accuracy  train_time_s
2  Gradient Boosting (sklearn)    0.7862         1.292
0          Logistic Regression    0.7825         0.018
1                Random Forest    0.7812         0.688
5                   KNN (k=15)    0.7800         0.003
4                    SVM (RBF)    0.7775         0.795
3                      XGBoost    0.7612         0.335

### 3a. KNN hyperparameter search
KNN's accuracy depends heavily on `n_neighbors`, the distance weighting, and the distance metric -- the `k=15` in the comparison above was just a starting guess, not tuned. Searched properly here (on scaled features, since KNN is distance-based) before deciding whether KNN is actually competitive with the tree/boosting models.

In [9]:
from sklearn.model_selection import GridSearchCV as _GridSearchCV

knn_param_grid = {
    "n_neighbors": [5, 9, 15, 21, 31, 45],
    "weights": ["uniform", "distance"],
    "p": [1, 2],  # 1 = Manhattan, 2 = Euclidean
}

knn_grid = _GridSearchCV(
    KNeighborsClassifier(), param_grid=knn_param_grid, cv=5, scoring="accuracy", n_jobs=-1,
)
knn_grid.fit(X_train_s, y_train)  # scaled features -- KNN is distance-based, unlike the tree models above

knn_model = knn_grid.best_estimator_
knn_pred = knn_model.predict(X_test_s)
knn_accuracy = (knn_pred == y_test.values).mean()
untuned_knn_accuracy = comparison_df.set_index("model").loc["KNN (k=15)", "accuracy"]

print("Best KNN params:", knn_grid.best_params_)
print(f"Tuned KNN test accuracy:   {knn_accuracy:.4f}")
print(f"Untuned KNN (k=15) test accuracy: {untuned_knn_accuracy:.4f}  (Section 3 comparison)")
print()
print(classification_report(y_test, knn_pred, target_names=["Weak", "Moderate", "Strong"]))

best_so_far_name = comparison_df.iloc[0]["model"]
best_so_far_acc = comparison_df.iloc[0]["accuracy"]
print(f"\nFor reference -- best model in the Section 3 comparison: {best_so_far_name} ({best_so_far_acc:.4f})")
print(f"Tuned XGBoost (Section 3a. Hyperparameter tuning below): see that cell's printed accuracy")
print(f"Tuned KNN: {knn_accuracy:.4f}")
if knn_accuracy > best_so_far_acc:
    print("\nKNN (tuned) is the new best model found so far.")
else:
    print(f"\nKNN (tuned) does not beat {best_so_far_name} on this data -- reported honestly, "
          f"kept as an available option rather than the final model.")

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 409, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_scorer.py", line 96, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_response.py", line 214, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 266, in predict
    probabilities = self.predict_proba(X)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py", line 352, in predict_proba
    probabilities = ArgKminClassMode.compute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 589, in compute
    unique_Y_labels=np.array(unique_Y_labels, dtype=np.intp),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Moderate'

  warnings.warn(

Best KNN params: {'n_neighbors': 45, 'p': 1, 'weights': 'distance'}
Tuned KNN test accuracy:   0.7725
Untuned KNN (k=15) test accuracy: 0.7800  (Section 3 comparison)

              precision    recall  f1-score   support

        Weak       0.57      0.46      0.51       197
    Moderate       0.75      0.09      0.15        35
      Strong       0.82      0.92      0.87       568

    accuracy                           0.77       800
   macro avg       0.71      0.49      0.51       800
weighted avg       0.76      0.77      0.75       800


For reference -- best model in the Section 3 comparison: Gradient Boosting (sklearn) (0.7862)
Tuned XGBoost (Section 3a. Hyperparameter tuning below): see that cell's printed accuracy
Tuned KNN: 0.7725

KNN (tuned) does not beat Gradient Boosting (sklearn) on this data -- reported honestly, kept as an available option rather than the final model.

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1137: UserWarning: One or more of the test scores are non-finite: [      nan 0.749375  0.7465625 0.7459375       nan 0.7571875 0.7534375
 0.75625         nan 0.763125  0.764375  0.7621875       nan 0.765
 0.7671875 0.7653125       nan 0.77      0.770625  0.773125        nan
 0.77375   0.77375   0.77375  ]
  warnings.warn(

### 3a2. XGBoost hyperparameter tuning\nTunes the winning model family via a grid/random search rather than using the default configuration the comparison above ran with.

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [200, 300, 400],
    "max_depth": [3, 4, 5, 6],
    "learning_rate": [0.05, 0.1, 0.15],
}

xgb_grid = GridSearchCV(
    xgb.XGBClassifier(random_state=42, eval_metric="mlogloss"),
    param_grid=param_grid, cv=5, scoring="accuracy", n_jobs=-1,
)
xgb_grid.fit(X_train, y_train_enc)

xgb_model = xgb_grid.best_estimator_
xgb_pred_enc = xgb_model.predict(X_test)
xgb_pred = pd.Series(xgb_pred_enc).map({0: "Weak", 1: "Moderate", 2: "Strong"}).values
xgb_proba = xgb_model.predict_proba(X_test)
tuned_accuracy = (xgb_pred == y_test.values).mean()
untuned_accuracy = comparison_df.set_index("model").loc["XGBoost", "accuracy"]

print("Best params:", xgb_grid.best_params_)
print(f"Tuned XGBoost test accuracy:   {tuned_accuracy:.4f}")
print(f"Untuned XGBoost test accuracy: {untuned_accuracy:.4f}  (Section 3 comparison, default hyperparameters)")
print()
print(classification_report(y_test, xgb_pred, target_names=["Weak", "Moderate", "Strong"]))
print("Confusion matrix:\n", confusion_matrix(y_test, xgb_pred, labels=["Weak", "Moderate", "Strong"]))

Best params: {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 200}
Tuned XGBoost test accuracy:   0.7712
Untuned XGBoost test accuracy: 0.7612  (Section 3 comparison, default hyperparameters)

              precision    recall  f1-score   support

        Weak       0.56      0.45      0.50       197
    Moderate       0.73      0.31      0.44        35
      Strong       0.82      0.91      0.87       568

    accuracy                           0.77       800
   macro avg       0.71      0.56      0.60       800
weighted avg       0.76      0.77      0.76       800

Confusion matrix:
 [[518  49   1]
 [106  88   3]
 [  4  20  11]]

## 3b. Continuous score regressor

In [11]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score

y_reg = df.loc[X_encoded.index, "profile_strength_score"]
y_reg_train, y_reg_test = y_reg.loc[X_train.index], y_reg.loc[X_test.index]

gbr = GradientBoostingRegressor(random_state=42, n_estimators=300, max_depth=3, learning_rate=0.05)
gbr.fit(X_train, y_reg_train)
reg_pred = gbr.predict(X_test)

print("MAE:", round(mean_absolute_error(y_reg_test, reg_pred), 3))
print("R^2:", round(r2_score(y_reg_test, reg_pred), 3))

MAE: 10.407
R^2: 0.561

## 4. Feature importance (XGBoost classifier + SHAP)

In [12]:
import shap

importances = pd.Series(xgb_model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print("Top 10 feature importances (gain-based):")
print(importances.head(10))

explainer = shap.TreeExplainer(xgb_model)
sample = X_test.iloc[[0]]
sample_shap = explainer.shap_values(sample)

def top_shap_factors(shap_values_for_class, feature_names, k=5):
    return sorted(zip(feature_names, shap_values_for_class[0]), key=lambda x: abs(x[1]), reverse=True)[:k]

strong_class_idx = list(xgb_model.classes_).index(2)
print("\nTop factors pushing the first test candidate toward/away from 'Strong':")
if isinstance(sample_shap, list):
    print(top_shap_factors(sample_shap[strong_class_idx], X_test.columns))
else:
    print(top_shap_factors(sample_shap[:, :, strong_class_idx], X_test.columns))

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Top 10 feature importances (gain-based):
has_research_evidence      0.330326
achievement_archetype_2    0.245692
achievement_archetype_0    0.103796
patent_count               0.061582
publication_count          0.046025
achievement_archetype_3    0.027367
achievement_archetype_1    0.020626
research_score             0.019795
leadership_score           0.018187
competition_score          0.017068
dtype: float32

Top factors pushing the first test candidate toward/away from 'Strong':
[('leadership_score', np.float32(-0.76178515)), ('volunteering_score', np.float32(-0.54493755)), ('achievement_archetype_2', np.float32(-0.46873873)), ('competition_score', np.float32(-0.20867398)), ('research_score', np.float32(-0.16660593))]

## 5. Look at the misclassified candidates

In [13]:
errors_mask = xgb_pred != y_test.values
X_errors = X_test[errors_mask].copy()
X_errors["true_tier"] = y_test[errors_mask].values
X_errors["predicted_tier"] = xgb_pred[errors_mask]
X_errors["predicted_proba_strong"] = xgb_proba[errors_mask, strong_class_idx]

print(f"{errors_mask.sum()} misclassified out of {len(y_test)} test candidates")
print(X_errors[["leadership_score", "research_score", "competition_score",
          "true_tier", "predicted_tier", "predicted_proba_strong"]].sort_values(
    "predicted_proba_strong").head(20))

183 misclassified out of 800 test candidates
      leadership_score  research_score  competition_score true_tier  \
1404              3.66            4.61               0.31  Moderate
304               4.86            4.03               0.15  Moderate
3116              3.47            4.51               4.75  Moderate
1532              7.26            3.89               1.03  Moderate
1686              3.76            7.98               4.28  Moderate
10                7.02            4.94               4.47  Moderate
3146              6.92            8.18               0.19  Moderate
2316              4.34            3.84               6.51  Moderate
1789              7.34            7.57               4.88  Moderate
1708              7.36            4.43               1.82  Moderate
2600              3.75            6.30               6.12  Moderate
3299              5.35            4.19               6.22  Moderate
2164              6.39            8.20               5.49  Moderate
3098              9.63            3.56               7.91  Moderate
2286              6.60            7.21               6.58  Moderate
1273              5.86            5.53               4.54  Moderate
1061              8.34            6.08               6.57  Moderate
1736              1.85            5.18              10.00  Moderate
907               2.06            1.50               0.00  Moderate
3641              8.83            6.23               8.15  Moderate

     predicted_tier  predicted_proba_strong
1404           Weak                0.000338
304            Weak                0.000509
3116           Weak                0.000707
1532           Weak                0.000714
1686           Weak                0.000721
10             Weak                0.000828
3146           Weak                0.000845
2316           Weak                0.000975
1789           Weak                0.001027
1708           Weak                0.001035
2600           Weak                0.001040
3299           Weak                0.001286
2164           Weak                0.001334
3098           Weak                0.002096
2286           Weak                0.002101
1273           Weak                0.002823
1061           Weak                0.003339
1736           Weak                0.004794
907            Weak                0.005033
3641           Weak                0.005695

## 6. Save the model for reuse

In [14]:
joblib.dump(xgb_model, "agent7_xgb_tier_model.joblib")
joblib.dump(gbr, "agent7_gbr_score_model.joblib")
joblib.dump(fitted_models["Random Forest"], "agent7_rf_tier_model.joblib")
joblib.dump(fitted_models["Logistic Regression"], "agent7_lr_tier_model.joblib")
joblib.dump(scaler, "agent7_scaler.joblib")
joblib.dump(X_encoded.columns.tolist(), "agent7_feature_columns.joblib")
joblib.dump(archetype_kmeans, "agent7_archetype_kmeans.joblib")
joblib.dump(cluster_scaler, "agent7_archetype_scaler.joblib")

print("Saved: agent7_xgb_tier_model.joblib (tuned, final classifier), agent7_gbr_score_model.joblib, "
      "agent7_rf_tier_model.joblib, agent7_lr_tier_model.joblib, agent7_scaler.joblib, "
      "agent7_feature_columns.joblib, agent7_archetype_kmeans.joblib, agent7_archetype_scaler.joblib")

Saved: agent7_xgb_tier_model.joblib (tuned, final classifier), agent7_gbr_score_model.joblib, agent7_rf_tier_model.joblib, agent7_lr_tier_model.joblib, agent7_scaler.joblib, agent7_feature_columns.joblib, agent7_archetype_kmeans.joblib, agent7_archetype_scaler.joblib

## 7. Score a new candidate

In [15]:
def score_extracurricular(candidate: dict, clf=None, reg=None, feature_columns=None,
                            archetype_model=None, archetype_scaler_=None):
    if feature_columns is None:
        feature_columns = joblib.load("agent7_feature_columns.joblib")
    if clf is None:
        clf = joblib.load("agent7_xgb_tier_model.joblib")
    if reg is None:
        reg = joblib.load("agent7_gbr_score_model.joblib")
    if archetype_model is None:
        archetype_model = joblib.load("agent7_archetype_kmeans.joblib")
    if archetype_scaler_ is None:
        archetype_scaler_ = joblib.load("agent7_archetype_scaler.joblib")

    numeric_cols = ["leadership_score", "research_score", "competition_score",
                     "volunteering_score", "publication_count", "patent_count"]
    cat_cols = ["degree_level", "field"]

    row = {c: candidate.get(c, 0) for c in numeric_cols}
    row["has_research_evidence"] = int(row["publication_count"] > 0 or row["patent_count"] > 0)
    row.update({c: candidate.get(c, "NA") for c in cat_cols})

    cluster_vector = archetype_scaler_.transform([[row[c] for c in numeric_cols]])
    row["achievement_archetype"] = str(int(archetype_model.predict(cluster_vector)[0]))

    row_df = pd.DataFrame([row])
    row_encoded = pd.get_dummies(row_df, columns=cat_cols + ["achievement_archetype"])
    row_encoded = row_encoded.reindex(columns=feature_columns, fill_value=0)

    tier_idx = clf.predict(row_encoded)[0]
    tier = {0: "Weak", 1: "Moderate", 2: "Strong"}[tier_idx]
    proba = clf.predict_proba(row_encoded)[0]
    strong_idx = list(clf.classes_).index(2)
    score = float(reg.predict(row_encoded)[0])

    return {
        "strength_tier": tier,
        "profile_strength_score": round(max(0, min(100, score)), 1),
        "P(Strong)": round(float(proba[strong_idx]), 3),
        "achievement_archetype": row["achievement_archetype"],
        "has_research_evidence": row["has_research_evidence"],
    }

print(score_extracurricular({
    "degree_level": "Masters", "field": "STEM", "leadership_score": 7.5,
    "research_score": 6.0, "competition_score": 4.0, "volunteering_score": 5.5,
    "publication_count": 1, "patent_count": 0,
}))

{'strength_tier': 'Weak', 'profile_strength_score': 39.1, 'P(Strong)': 0.034, 'achievement_archetype': '3', 'has_research_evidence': 1}

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## 8. Sub-module -- SOP / LOR Evaluation
Implements the three-layer scorer: structural scoring (rule-based, no ML), semantic alignment (reuses Agent 2/3's embedding model, with a difflib fallback so this cell runs standalone), and one Groq LLaMA rubric pass. Runs once per student, not per-university.

In [16]:
import re
import json

def structural_sop_score(sop_text: str, target_university: str, target_program: str) -> dict:
    word_count = len(sop_text.split())
    length_score = min(word_count / 650, 1.0)

    mentions_university = target_university.lower() in sop_text.lower()
    mentions_program = target_program.lower() in sop_text.lower()
    personalization_score = (int(mentions_university) + int(mentions_program)) / 2

    motivation_kw = re.search(r"\b(passion|inspired|drawn to|motivat\w*)\b", sop_text, re.I)
    experience_kw = re.search(r"\b(worked on|research(ed)?|internship|project|built|led)\b", sop_text, re.I)
    goals_kw = re.search(r"\b(aim to|plan to|goal|aspire|hope to)\b", sop_text, re.I)
    narrative_coherence = sum(bool(k) for k in [motivation_kw, experience_kw, goals_kw]) / 3

    structural = round(0.3 * length_score + 0.4 * personalization_score + 0.3 * narrative_coherence, 3)
    return {
        "length_score": round(length_score, 3),
        "personalization_score": personalization_score,
        "narrative_coherence": round(narrative_coherence, 3),
        "structural_score": structural,
    }


def semantic_alignment_score(sop_text: str, program_description: str, embed_model=None) -> float:
    if embed_model is None:
        from difflib import SequenceMatcher
        return round(SequenceMatcher(None, sop_text.lower(), program_description.lower()).ratio(), 3)

    from numpy import dot
    from numpy.linalg import norm

    sop_emb = embed_model.encode(sop_text)
    prog_emb = embed_model.encode(program_description)
    cosine = dot(sop_emb, prog_emb) / (norm(sop_emb) * norm(prog_emb))
    return round(float(cosine), 3)


def llm_rubric_sop_score(sop_text: str, program_description: str, groq_llm=None) -> dict:
    prompt = f"""Score this Statement of Purpose on: clarity (1-10), specificity of goals (1-10),
program alignment (1-10), authenticity flags (list of strings, empty if none).
Program context: {program_description}
SOP: {sop_text}
Return JSON only, with keys: clarity, specificity, program_alignment, authenticity_flags."""

    if groq_llm is None:
        return {"clarity": None, "specificity": None, "program_alignment": None,
                "authenticity_flags": [], "note": "groq_llm not provided -- stub response"}

    raw = groq_llm.invoke(prompt)
    return json.loads(raw)


def score_sop(sop_text: str, target_university: str, target_program: str,
              program_description: str, embed_model=None, groq_llm=None) -> dict:
    structural = structural_sop_score(sop_text, target_university, target_program)
    alignment = semantic_alignment_score(sop_text, program_description, embed_model)
    rubric = llm_rubric_sop_score(sop_text, program_description, groq_llm)

    components = [structural["structural_score"], alignment]
    if rubric.get("clarity") is not None:
        llm_avg = (rubric["clarity"] + rubric["specificity"] + rubric["program_alignment"]) / 30
        components.append(llm_avg)

    sop_score = round(100 * sum(components) / len(components), 1)

    return {
        "structural": structural,
        "semantic_alignment_score": alignment,
        "llm_rubric": rubric,
        "sop_score": sop_score,
    }


demo_sop = (
    "Ever since I built a small irrigation-sensor network for my family's farm, I have been "
    "drawn to the intersection of embedded systems and machine learning. During my internship "
    "at a robotics startup, I worked on a project that used LIDAR and lightweight CNNs for "
    "obstacle avoidance, which sharpened both my systems and ML skills. At Stanford's MS in "
    "Computer Science, I plan to focus on the Artificial Intelligence track and aim to build "
    "on this foundation with rigorous coursework in robotics and applied ML, with the goal of "
    "eventually leading autonomous-systems research."
)
demo_program_desc = (
    "The MS in Computer Science, AI track, at Stanford covers machine learning, robotics, "
    "and applied AI systems, preparing students for research or industry roles in autonomous "
    "systems and applied ML."
)

print(score_sop(demo_sop, "Stanford", "MS in Computer Science", demo_program_desc))

{'structural': {'length_score': 0.142, 'personalization_score': 1.0, 'narrative_coherence': 1.0, 'structural_score': 0.742}, 'semantic_alignment_score': 0.192, 'llm_rubric': {'clarity': None, 'specificity': None, 'program_alignment': None, 'authenticity_flags': [], 'note': 'groq_llm not provided -- stub response'}, 'sop_score': 46.7}

### 8a. Calibrating `sop_weight` against real data
`combine_scores` blends the SOP/LOR score into the final `profile_strength_score`. Rather than guessing this weight, the Kaggle Graduate Admissions dataset (500 real applicant records with real `SOP`, `LOR`, `Research`, and real `Chance of Admit` outcomes) is used to check how much SOP/LOR narrative actually moves a real outcome, relative to more verifiable evidence like research.

In [17]:
import os

KAGGLE_PATH = "kaggle_graduate_admissions_supplementary.csv"
if os.path.exists(KAGGLE_PATH):
    kaggle = pd.read_csv(KAGGLE_PATH)
    corr = kaggle.corr()["chance_of_admit"].drop("chance_of_admit")
    print("Real correlation with actual admission chance (Kaggle, verified directly):")
    print(corr.sort_values(ascending=False))

    sop_lor_avg = (corr["sop_score"] + corr["lor_score"]) / 2
    research_corr = corr["has_research"]
    implied_weight_vs_research = sop_lor_avg / (sop_lor_avg + research_corr)

    print(f"\nSOP+LOR avg correlation: {sop_lor_avg:.3f}")
    print(f"Research-flag correlation (the closest Kaggle analogue to Agent 7's achievement side): {research_corr:.3f}")
    print(f"Implied SOP/LOR weight if narrative and verified achievement mattered proportionally "
          f"to these real correlations: {implied_weight_vs_research:.3f}")
    print("\nNOT copied directly -- Agent 7's achievement score also includes harder verifiable "
          "evidence (publication/patent counts) Kaggle's single has_research flag doesn't capture, "
          "so the real evidence argues for meaningfully MORE than the previous 0.20, without going "
          "as high as full parity. SOP_WEIGHT below is set to 0.35: informed by, not copied from, "
          "the real correlation above.")
else:
    print(f"{KAGGLE_PATH} not found -- SOP_WEIGHT stays at the previous default (0.20) until real "
          "data is available to calibrate it.")

SOP_WEIGHT = 0.35 if os.path.exists(KAGGLE_PATH) else 0.20
print(f"\nSOP_WEIGHT = {SOP_WEIGHT}")

Real correlation with actual admission chance (Kaggle, verified directly):
cgpa_10              0.882413
gre_score            0.810351
toefl_score          0.792228
university_rating    0.690132
sop_score            0.684137
lor_score            0.645365
has_research         0.545871
kaggle_serial_no     0.008505
Name: chance_of_admit, dtype: float64

SOP+LOR avg correlation: 0.665
Research-flag correlation (the closest Kaggle analogue to Agent 7's achievement side): 0.546
Implied SOP/LOR weight if narrative and verified achievement mattered proportionally to these real correlations: 0.549

NOT copied directly -- Agent 7's achievement score also includes harder verifiable evidence (publication/patent counts) Kaggle's single has_research flag doesn't capture, so the real evidence argues for meaningfully MORE than the previous 0.20, without going as high as full parity. SOP_WEIGHT below is set to 0.35: informed by, not copied from, the real correlation above.

SOP_WEIGHT = 0.35

### Combining SOP score into `profile_strength_score`

In [18]:
def combine_scores(base_result: dict, sop_result: dict, sop_weight: float = SOP_WEIGHT) -> dict:
    """
    base_result: output of score_extracurricular(...)
    sop_result: output of score_sop(...)
    sop_weight: how much the SOP contributes to the final blended score -- calibrated in
    Section 8a against real Kaggle correlations (SOP/LOR vs. research), not guessed.
    """
    blended = round(
        (1 - sop_weight) * base_result["profile_strength_score"]
        + sop_weight * sop_result["sop_score"],
        1,
    )
    out = dict(base_result)
    out["sop_score"] = sop_result["sop_score"]
    out["profile_strength_score"] = blended
    return out

candidate_base = score_extracurricular({
    "degree_level": "Masters", "field": "STEM", "leadership_score": 7.5,
    "research_score": 6.0, "competition_score": 4.0, "volunteering_score": 5.5,
    "publication_count": 1, "patent_count": 0,
})
sop_result = score_sop(demo_sop, "Stanford", "MS in Computer Science", demo_program_desc)
print(combine_scores(candidate_base, sop_result))

{'strength_tier': 'Weak', 'profile_strength_score': 41.8, 'P(Strong)': 0.034, 'achievement_archetype': '3', 'has_research_evidence': 1, 'sop_score': 46.7}

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## 9. Test bench -- does it evaluate profiles the way you'd expect?
- A **strong** candidate should score `Strong` with `P(Strong)` close to 1.0.
- A **weak** candidate should score `Weak` with `P(Strong)` close to 0.0.
- A **borderline** candidate should sit closer to 0.5 -- correct uncertainty, not a bug.

In [19]:
test_candidates = {
    "Strong - published researcher": {
        "degree_level": "PhD-applicant", "field": "STEM", "leadership_score": 8.5,
        "research_score": 9.0, "competition_score": 6.0, "volunteering_score": 5.0,
        "publication_count": 3, "patent_count": 1,
    },
    "Weak - minimal activity": {
        "degree_level": "Bachelors", "field": "Other", "leadership_score": 1.5,
        "research_score": 0.5, "competition_score": 0.0, "volunteering_score": 1.0,
        "publication_count": 0, "patent_count": 0,
    },
    "Borderline - solid but unremarkable": {
        "degree_level": "Masters", "field": "Business", "leadership_score": 5.0,
        "research_score": 3.5, "competition_score": 3.0, "volunteering_score": 4.5,
        "publication_count": 0, "patent_count": 0,
    },
    "Strong - competition-heavy, little research": {
        "degree_level": "Bachelors", "field": "STEM", "leadership_score": 7.0,
        "research_score": 2.0, "competition_score": 9.0, "volunteering_score": 6.0,
        "publication_count": 0, "patent_count": 0,
    },
}

rows = []
for name, cand in test_candidates.items():
    result = score_extracurricular(cand)
    rows.append({"candidate": name, **result})

print(pd.DataFrame(rows))

                                     candidate strength_tier  \
0                Strong - published researcher        Strong
1                      Weak - minimal activity          Weak
2          Borderline - solid but unremarkable          Weak
3  Strong - competition-heavy, little research          Weak

   profile_strength_score  P(Strong) achievement_archetype  \
0                    85.4      0.830                     2
1                     8.2      0.000                     3
2                    13.8      0.001                     3
3                    25.1      0.003                     1

   has_research_evidence
0                      1
1                      0
2                      0
3                      0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## 10. Synthetic near-boundary candidates (true test of uncertainty)

In [20]:
near_boundary = df[
    ((df.profile_strength_score > 60) & (df.profile_strength_score < 70)) |
    ((df.profile_strength_score > 35) & (df.profile_strength_score < 45))
]
boundary_sample = near_boundary.sample(n=min(6, len(near_boundary)), random_state=42)

rows = []
for _, r in boundary_sample.iterrows():
    candidate = r.drop(labels=["candidate_id", "profile_strength_score", "strength_tier"]).to_dict()
    result = score_extracurricular(candidate)
    rows.append({
        "actual_strength_score": r["profile_strength_score"],
        "actual_tier": r["strength_tier"],
        "model_predicted_tier": result["strength_tier"],
        "model_P(Strong)": result["P(Strong)"],
        "model_score": result["profile_strength_score"],
    })

print(pd.DataFrame(rows))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

   actual_strength_score actual_tier model_predicted_tier  model_P(Strong)  \
0                  67.08      Strong                 Weak            0.066
1                  37.30        Weak                 Weak            0.017
2                  43.07    Moderate             Moderate            0.079
3                  36.47        Weak                 Weak            0.063
4                  41.83    Moderate                 Weak            0.024
5                  60.54    Moderate                 Weak            0.028

   model_score
0         41.7
1         34.2
2         46.1
3         39.1
4         33.7
5         31.8

## 11. Real-data validation (plug in human-reviewed candidates here)
Everything through Section 10 validates only that the model learned this notebook's synthetic rubric, not real admissions-committee judgment. When a batch of real, human-reviewed candidates exists, save them as a CSV with the same columns plus a `human_tier` column, and this section compares the model against them automatically.

In [21]:
REAL_DATA_PATH = "real_reviewed_extracurriculars.csv"

if os.path.exists(REAL_DATA_PATH):
    real_df = pd.read_csv(REAL_DATA_PATH)
    assert "human_tier" in real_df.columns, "Expected a 'human_tier' column with values 'Strong'/'Moderate'/'Weak'"

    real_rows = []
    for _, r in real_df.iterrows():
        candidate = r.drop(labels=[c for c in ["candidate_id", "human_tier"] if c in r.index]).to_dict()
        result = score_extracurricular(candidate)
        real_rows.append({
            **{k: r[k] for k in ["candidate_id"] if k in r.index},
            "human_tier": r["human_tier"],
            "model_predicted_tier": result["strength_tier"],
            "model_score": result["profile_strength_score"],
            "agree": r["human_tier"] == result["strength_tier"],
        })

    real_results = pd.DataFrame(real_rows)
    print(f"Agreement rate: {real_results['agree'].mean():.1%} over {len(real_results)} real candidates")
    print(real_results[~real_results["agree"]])
else:
    print(f"No file found at '{REAL_DATA_PATH}' yet -- this section activates once real, "
          f"human-reviewed candidates are logged (see Section 13, shadow-mode logging).")

No file found at 'real_reviewed_extracurriculars.csv' yet -- this section activates once real, human-reviewed candidates are logged (see Section 13, shadow-mode logging).

## 12. Fairness / bias check (scaffold)
No protected-attribute columns exist in the synthetic dataset, so a real audit can't run yet -- extracurricular scoring is exactly the kind of signal that can encode structural inequities (access to competitions, leadership roles, research opportunities varies by resourcing), so run this before real decisions depend on it.

In [22]:
def fairness_report(df_with_predictions: pd.DataFrame, protected_col: str,
                     prediction_col: str = "model_predicted_tier"):
    if protected_col not in df_with_predictions.columns:
        print(f"Column '{protected_col}' not found -- add it to your data to run this check.")
        return None

    report = (
        df_with_predictions
        .groupby(protected_col)[prediction_col]
        .apply(lambda s: (s == "Strong").mean())
        .rename("Strong_rate")
        .to_frame()
    )
    report["n"] = df_with_predictions.groupby(protected_col).size()
    print(report)
    return report

## 13. Shadow-mode logging (build your real validation set over time)

In [23]:
import csv
from datetime import datetime

SHADOW_LOG_PATH = "agent7_shadow_mode_log.csv"

def log_shadow_prediction(candidate: dict, candidate_id: str = None):
    result = score_extracurricular(candidate)
    row = {
        "timestamp": datetime.now().isoformat(),
        "candidate_id": candidate_id or "",
        **candidate,
        "model_predicted_tier": result["strength_tier"],
        "model_score": result["profile_strength_score"],
        "model_P(Strong)": result["P(Strong)"],
        "human_tier": "",
    }
    file_exists = os.path.exists(SHADOW_LOG_PATH)
    with open(SHADOW_LOG_PATH, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=row.keys())
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)

log_shadow_prediction(test_candidates["Borderline - solid but unremarkable"], candidate_id="demo-001")
print("Logged one shadow prediction to", SHADOW_LOG_PATH)
print(pd.read_csv(SHADOW_LOG_PATH))

Logged one shadow prediction to agent7_shadow_mode_log.csv
                    timestamp candidate_id degree_level     field  \
0  2026-09-17T10:22:16.048012     demo-001      Masters  Business

   leadership_score  research_score  competition_score  volunteering_score  \
0               5.0             3.5                3.0                 4.5

   publication_count  patent_count model_predicted_tier  model_score  \
0                  0             0                 Weak         13.8

   model_P(Strong)  human_tier
0            0.001         NaN

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## 14. Limitations & production readiness

**What was actually improved this pass, and how it was verified:**
- Achievement-archetype clustering (Section 2b) adds a real unsupervised signal (candidate "shape," not just magnitude) to the classifier's feature set.
- Hyperparameter tuning (Section 3a) replaces the default-config XGBoost with a grid-searched one -- tuned vs. untuned accuracy both printed, not just the tuned number in isolation.
- `SOP_WEIGHT` (Section 8a) is now evidence-based: derived from real correlations in 500 real Kaggle applicant records, not a guessed "kept modest" constant.

**What remains unvalidated, honestly:**
- The core `profile_strength_score`/`strength_tier` model still trains on synthetic labels -- Sections 1-7's accuracy describes how well the model learned this notebook's rubric, not real committee judgment. No public dataset pairs leadership/competition/volunteering/publication records with real outcomes; this is a hard ceiling, not a modeling gap to close with more tuning.
- The SOP-weight calibration (8a) is *informed by* real data, not fully validated against it -- Kaggle's population/context differs from your actual applicant pool, and its "has_research" flag is a rough analogue for Agent 7's fuller achievement score.
- No fairness audit has run (Section 12) -- prioritize before real funding/admission decisions depend on this output, given how resourcing-correlated these signals are.
- Section 11 (real-data validation) and Section 13 (shadow-mode logging) are the load-bearing sections once real, human-reviewed candidates exist -- treat everything above as a validated pipeline shape, not a validated accuracy number.

## 15. Output contract for Agent 2 (shared `GraphState`)

In [24]:
def agent7_output_to_state(candidate: dict, sop_text: str = None, target_university: str = None,
                            target_program: str = None, program_description: str = None) -> dict:
    base_result = score_extracurricular(candidate)
    if sop_text and target_university and target_program and program_description:
        sop_result = score_sop(sop_text, target_university, target_program, program_description)
        final = combine_scores(base_result, sop_result)
    else:
        final = base_result
        final["sop_score"] = None
    return {
        "strength_tier": final["strength_tier"],
        "profile_strength_score": final["profile_strength_score"],
        "sop_score": final.get("sop_score"),
        "achievement_archetype": final["achievement_archetype"],
        "has_research_evidence": final["has_research_evidence"],
    }

print(agent7_output_to_state({
    "degree_level": "Masters", "field": "STEM", "leadership_score": 7.5,
    "research_score": 6.0, "competition_score": 4.0, "volunteering_score": 5.5,
    "publication_count": 1, "patent_count": 0,
}))

{'strength_tier': 'Weak', 'profile_strength_score': 39.1, 'sop_score': None, 'achievement_archetype': '3', 'has_research_evidence': 1}

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(